# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "impressionist"
  s.version = "1.0.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["cowboycoded"]
  s.date = "2012-03-06"
  s.description = "Log impressions from controller actions or from a model"
  s.email = "john.mcaliley@gmail.com"
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.md"
  ]
  s.files = [
    "CHANGELOG.rdoc",
    "Gemfile",
    "LICENSE.txt",
    "README.md",
    "Rakefile",
    "VERSION",
    "app/controllers/impressionist_controller.rb",
    "app/models/impression.rb",
    "app/models/impressionist/bots.rb",
    "app/models/impressionist/impressionable.rb",
    "config/routes.rb",
    "impressionist.gemspec",
    "lib/generators/impressionist/impressionist_generator.rb",
    "lib/generators/impressionist/templates/create_impressions_table.rb",
    "lib/impressionist.rb",
    "lib/impressionist/bots.rb",
    "lib/impressionist/engine.rb",
    "lib/impressionist/railties/tasks.rake",
    "logo.png",
    "upgrade_migrations/version_0_3_0.rb",
    "upgrade_migrations/version_0_4_0.rb"
  ]
  s.homepage = "https://github.com/charlotte-ruby/impressionist"
  s.licenses = ["MIT"]
  s.require_paths = ["lib"]
  s.rubygems_version = "1.8.17"
  s.summary = "Easy way to log impressions"

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<jeweler>, [">= 1.5.1"])
      s.add_development_dependency(%q<rcov>, [">= 0"])
      s.add_development_dependency(%q<rdoc>, [">= 2.4.2"])
      s.add_development_dependency(%q<shoulda>, [">= 0"])
    else
      s.add_dependency(%q<jeweler>, [">= 1.5.1"])
      s.add_dependency(%q<rcov>, [">= 0"])
      s.add_dependency(%q<rdoc>, [">= 2.4.2"])
      s.add_dependency(%q<shoulda>, [">= 0"])
    end
  else
    s.add_dependency(%q<jeweler>, [">= 1.5.1"])
    s.add_dependency(%q<rcov>, [">= 0"])
    s.add_dependency(%q<rdoc>, [">= 2.4.2"])
    s.add_dependency(%q<shoulda>, [">= 0"])
  end
end

