# frozen_string_literal: false

source 'https://rubygems.org'

gem 'public_suffix', '< 1.5.0'
gem 'rails', '>= 5'
gem 'rake', '< 11.0'

gem 'impressionist', path: '../../'

platforms :ruby, :mswin, :mingw do
  gem 'bson_ext'
  gem 'mongoid', '~> 7.1'
  gem 'mysql2'
  gem 'pg'
  gem 'sqlite3', '~> 1.3.5'
end

gem 'json'

# Gems used only for assets and not required
# in production environments by default.
group :assets do
  gem 'coffee-rails', '~> 5.0'
  gem 'sass-rails',   '~> 6.0'

  # See https://github.com/sstephenson/execjs#readme for more supported runtimes
  # gem 'therubyracer'

  gem 'uglifier', '>= 1.0.3'
end

group :development, :test do
  gem 'autotest-notification'
  gem 'pry'
  gem 'rspec-rails', '~> 2.14.0'
  gem 'spork'

  # test/unit has been removed by default in Ruby 2.2.x+
  gem 'test-unit'
end

group :test do
  gem 'capybara'
  gem 'simplecov'
  gem 'systemu'
end

# gem 'activerecord-sqlite3-adapter'
gem 'bigdecimal', '1.4.2'
gem 'friendly_id', '~> 5.0'
gem 'jquery-rails'
