source 'https://rubygems.org'

gem 'rails', '3.2.12'

gem 'impressionist', :path => '../../'

platforms :jruby do
  gem 'activerecord-jdbcsqlite3-adapter'
  gem 'jdbc-sqlite3'
  gem 'jruby-openssl'
end

platforms :ruby, :mswin, :mingw do
  gem 'pg'
  gem 'sqlite3'
  gem 'mysql2'
  gem "mongoid", "~> 3.1.4"
  gem 'bson_ext'
end

gem 'json'

# Gems used only for assets and not required
# in production environments by default.
group :assets do
  gem 'sass-rails',   '~> 3.2.3'
  gem 'coffee-rails', '~> 3.2.1'

  # See https://github.com/sstephenson/execjs#readme for more supported runtimes
  # gem 'therubyracer'

  gem 'uglifier', '>= 1.0.3'
end

group :development, :test do
  gem 'autotest-notification'
  gem 'rspec-rails'
  gem 'spork'
end

group :test do
  gem 'simplecov'
  gem 'systemu'
  gem 'capybara', '~> 2.0.0'
end

gem 'jquery-rails'

