source 'http://rubygems.org'

gem 'rails', '3.1'
gem 'sqlite3-ruby', :require => 'sqlite3'
gem 'impressionist', :path => '../'

group :development, :test do
  gem 'autotest-notification'
  gem 'capybara'
  gem 'database_cleaner'
  gem 'httpclient'
  gem 'launchy'
  gem 'mongrel', '1.2.0.pre2'
  gem 'rspec'
  gem 'rspec-rails'
  gem 'shoulda'
  gem 'spork'
  gem 'systemu'
end

group :test do
  gem 'cucumber-rails'
end
