# Add your own tasks in files placed in lib/tasks ending in .rake,
# for example lib/tasks/capistrano.rake, and they will automatically be available to Rake.

#require File.expand_path('../config/application', __FILE__)

#Dummy::Application.load_tasks

require 'rake/testtask'

__PATTERN__ = 'test/**/*_spec.rb'

task default: :test

Rake::TestTask.new do |task|
  task.libs << ['test','app/controllers', 'app/models', 'app/views']
  task.pattern       = __PATTERN__
  task.test_files = FileList[__PATTERN__]
  task.verbose    = false
end
